# Generated by Django 4.2.7 on 2024-01-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_productrating_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='has_variants',
            field=models.BooleanField(default=False),
        ),
    ]
