# Generated by Django 4.2.7 on 2024-01-05 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productinventory_has_variants'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='unique_product_variant',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='product',
        ),
    ]
