# Generated by Django 4.2.7 on 2024-01-14 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_productvariant_unique_product_variant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='size',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color', related_query_name='color', to='product.productinventory'),
        ),
        migrations.CreateModel(
            name='ProductVariantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('v_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v_info', related_query_name='v_info', to='product.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariantColorImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='variant_product_images/')),
                ('v_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v_images', related_query_name='v_image', to='product.productvariant')),
            ],
            options={
                'ordering': ['v_color_id'],
            },
        ),
    ]
