# Generated by Django 4.2.7 on 2024-01-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_productvariant_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantcolorimages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariantcolorimages',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariantinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariantinfo',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
