# Generated by Django 4.2.7 on 2024-01-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_remove_product_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
