# Generated by Django 4.2.7 on 2024-01-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_remove_productinventory_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='color_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
