# Generated by Django 4.2.7 on 2024-01-17 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_productinventory_color_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductChildVariantInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, null=True)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('supplier_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductParentVariantInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='color_name',
        ),
        migrations.DeleteModel(
            name='ProductVariantInventory',
        ),
        migrations.AddField(
            model_name='productparentvariantinventory',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', related_query_name='variants_inventory', to='product.productinventory'),
        ),
        migrations.AddField(
            model_name='productchildvariantinventory',
            name='parent_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_variant', to='product.productparentvariantinventory'),
        ),
    ]
