# Generated by Django 4.2.7 on 2024-01-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_productchildvariantinventory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariantcolorimages',
            name='v_color',
        ),
        migrations.RemoveField(
            model_name='productvariantinfo',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='productvariantinfo',
            name='v_color',
        ),
        migrations.RemoveField(
            model_name='productchildvariantinventory',
            name='description',
        ),
        migrations.AddField(
            model_name='productinventory',
            name='has_variants',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='productparentvariantinventory',
            name='default',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
        migrations.DeleteModel(
            name='ProductVariantColorImages',
        ),
        migrations.DeleteModel(
            name='ProductVariantInfo',
        ),
    ]
