# Generated by Django 4.2.7 on 2024-01-17 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_remove_productvariantcolorimages_v_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantColorImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='variant_product_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('parent_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', related_query_name='image', to='product.productparentvariantinventory')),
            ],
            options={
                'ordering': ['parent_variant_id'],
            },
        ),
    ]
