# Generated by Django 4.2.7 on 2024-01-17 15:16

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_productvariantcolorimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_image',
        ),
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productinventory'),
        ),
        migrations.CreateModel(
            name='ProductParentVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('main_image', models.ImageField(upload_to='product_images/')),
                ('inventory_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productparentvariantinventory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color', related_query_name='color', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductChildVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inventory_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productchildvariantinventory')),
                ('parent_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', related_query_name='child', to='product.productparentvariant')),
            ],
        ),
        migrations.AlterField(
            model_name='productvariantcolorimages',
            name='parent_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', related_query_name='image', to='product.productparentvariant'),
        ),
    ]
