# Generated by Django 4.2.7 on 2024-01-18 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_remove_product_main_image_product_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productchildvariant',
            name='inventory_child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inv_child', related_query_name='inv_child', to='product.productchildvariantinventory'),
        ),
        migrations.AlterField(
            model_name='productchildvariant',
            name='parent_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', related_query_name='parent', to='product.productparentvariant'),
        ),
        migrations.AlterField(
            model_name='productparentvariant',
            name='inventory_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inv_parent', related_query_name='inv_parent', to='product.productparentvariantinventory'),
        ),
    ]
