# Generated by Django 4.2.7 on 2024-01-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_remove_productparentvariantinventory_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productparentvariant',
            name='default',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
