# Generated by Django 4.2.7 on 2024-01-24 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_alter_productparentvariant_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.discount'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.discount'),
        ),
        migrations.AddField(
            model_name='productchildvariant',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.discount'),
        ),
        migrations.AddField(
            model_name='productparentvariant',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.discount'),
        ),
    ]
