# Generated by Django 4.2.7 on 2024-02-19 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0026_product_discount_productcategory_discount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategory",
            name="discount",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.discount",
            ),
        ),
    ]
