# Generated by Django 4.2.7 on 2024-01-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0002_referralcodehistory_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralcodehistory',
            name='joining_rewards',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='referralcodehistory',
            name='referral_rewards',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
