# Generated by Django 4.2.7 on 2024-01-25 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_alter_orderitems_modified_at'),
        ('cadmin', '0003_referralcodehistory_joining_rewards_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralRewardSchemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('referral', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='referralcodehistory',
            name='new_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code_received', to='user.user'),
        ),
        migrations.AlterField(
            model_name='referralcodehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_codes_given', to='user.user'),
        ),
    ]
