# Generated by Django 4.2.7 on 2024-02-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0005_referralcodehistory_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='banners/')),
                ('link', models.URLField()),
                ('text', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
