# Generated by Django 4.2.7 on 2024-02-08 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0006_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
