# Generated by Django 4.2.7 on 2023-12-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_wallet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.TextField(),
        ),
    ]
