# Generated by Django 4.2.7 on 2023-12-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_orderdetails_paymentdetails_orderitems_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettranslation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
