# Generated by Django 4.2.7 on 2023-12-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_orderdetails_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='address',
            field=models.IntegerField(default=0),
        ),
    ]
