# Generated by Django 4.2.7 on 2023-12-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_orderdetails_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
