# Generated by Django 4.2.7 on 2023-12-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_orderitems_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='refund',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='status',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='refund',
            field=models.CharField(blank=True, choices=[('Cancel', 'Cancel'), ('Approve', 'Approve')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='status',
            field=models.CharField(blank=True, choices=[('Return', 'Return'), ('Cancel', 'Cancel')], max_length=10, null=True),
        ),
    ]
