# Generated by Django 4.2.7 on 2023-12-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_orderdetails_refund_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
    ]
