# Generated by Django 4.2.7 on 2023-12-30 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
