# Generated by Django 4.2.7 on 2023-12-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_orderitems_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
