# Generated by Django 4.2.7 on 2024-01-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_order_address_id_order_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
