# Generated by Django 4.2.7 on 2024-01-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_order_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adminstatus',
            field=models.CharField(default='user', max_length=10),
        ),
    ]
