# Generated by Django 4.2.7 on 2024-01-21 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_alter_productparentvariant_default'),
        ('user', '0022_orderitems_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='variant',
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productchildvariant'),
        ),
    ]
