# Generated by Django 4.2.7 on 2024-01-21 18:47

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_remove_orderitems_variant_alter_orderitems_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='modified_at',
            field=models.DateField(default=user.models.get_default_date),
        ),
    ]
