# Generated by Django 4.2.7 on 2024-01-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_orderitems_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
