# Generated by Django 4.2.7 on 2024-02-03 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_alter_orderitems_modified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.PositiveBigIntegerField()),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('order_items', models.ManyToManyField(to='user.orderitems')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
