# Generated by Django 4.2.7 on 2024-02-04 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_invoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
