# Generated by Django 4.2.7 on 2024-02-04 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_invoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
