# Generated by Django 4.2.7 on 2024-02-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_invoiceitems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoiceItems',
        ),
    ]
