# Generated by Django 4.2.7 on 2024-02-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0033_delete_invoiceitems"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=100),
        ),
    ]
