# Generated by Django 4.2.7 on 2024-02-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0034_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
