# Generated by Django 4.2.7 on 2023-12-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_coupon_appliedcoupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='count',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
