# Generated by Django 4.2.7 on 2023-12-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_coupon_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedcoupon',
            name='successfully_applied',
            field=models.BooleanField(default=True),
        ),
    ]
