# Generated by Django 4.2.7 on 2024-01-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_appliedcoupon_successfully_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
