# Generated by Django 4.2.7 on 2024-01-21 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_orderitems_variant'),
        ('product', '0025_alter_productparentvariant_default'),
        ('orders', '0007_cart_variant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cart',
            name='child_variant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='product.productchildvariant'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'child_variant')},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='variant',
        ),
    ]
